version: "3.9"
services:
  postgres:
    image: ghcr.io/ttscience/postgres-temporal-tables/postgres-temporal-tables:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: R -e "testthat::test_package('unbiased')"
