#!/bin/bash

set -e

DB_NAME_SUFFIX="__test"

ORIGINAL_DB_NAME="$POSTGRES_DB"
POSTGRES_DB="${ORIGINAL_DB_NAME}${DB_NAME_SUFFIX}"
UNBIASED_PORT=3899
UNBIASED_HOST="127.0.0.1"

echo "Running provided command in test context"

export POSTGRES_DB UNBIASED_PORT UNBIASED_HOST

"$@"