# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ["R/**"]

name: Document

jobs:
  document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install CI extras (roxygen2)
        run: |
          pkgs <- c("roxygen2")
          for (p in pkgs) {
            if (!requireNamespace(p, quietly = TRUE)) {
              install.packages(p, repos = "https://packagemanager.posit.co/cran/latest")
            }
          }
        shell: Rscript {0}

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "Update documentation" || echo "No changes to commit"
          git pull --ff-only
          git push origin
